capture/urls.py
from django.urls import path

from . import views

app_name = 'capture'
urlpatterns = [
    # ex: /capture/
    path('', views.index, name='index'),
    # ex: /capture/5/
    path('<int:capture_id>/', views.detail, name='detail'),
    # ex: /capture/all
    path('all/', views.all, name='all'),
    # ex: /capture/capture
    path('capture/', views.capture, name='capture'),
    # ex: /capture/bin
    path('capture/bin', views.paper_bin, name='paper_bin'),
    # ex; /capture/delete/5
    path('delete/<int:capture_id>', views.delete, name='delete'),
    # ex; /capture/undelete/5
    path('undelete/<int:capture_id>', views.undelete, name='undelete'),
    # ex; /capture/logbook
    path('capture/logbook', views.logbook, name='logbook'),
    # ex; /capture/log_item/5
    path('capture/log_item/<int:capture_id>', views.log_item, name='log_item'),
    # ex; /capture/today
    path('capture/today', views.today, name='today'),
    # ex; /capture/calendar
    path('capture/calendar', views.calendar, name='calendar'),
    # ex; /capture/anytime
    path('capture/anytime', views.anytime, name='anytime'),
    # ex; /capture/projects
    path('capture/projects', views.projects, name='projects'),
]

gtd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('capture/', include('capture.urls')),
    path('admin/', admin.site.urls),
]

capture/models.py
import datetime

from django.db import models
from django.utils import timezone

class Capture(models.Model):
    capture_text = models.CharField(max_length=500)
    capture_date = models.DateTimeField('date captured')
    notes = models.CharField(null=True, blank=True, max_length=2000)
    category = models.SmallIntegerField(default=0)
    status = models.SmallIntegerField(default=0)
    project = models.CharField(null=True, blank=True, max_length=500)
    due_date = models.DateField(null=True, blank=True)
    any_time = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.capture_text
    def was_published_recently(self):
        return self.capture_date >= timezone.now() - datetime.timedelta(days=1)

capture/views.py
import datetime

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone

from .models import Capture

# Create your views here.
def index(request):
    all_capture_list = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).order_by('-capture_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_capture_list': all_capture_list,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/index.html', context)

def paper_bin(request):
    paper_bin_list = Capture.objects.filter(category=8).order_by('-capture_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'paper_bin_list': paper_bin_list,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/index.html', context)

def detail(request, capture_id):
    all_project_items = Capture.objects.filter(status=0, category=1).order_by('project')
    capture = get_object_or_404(Capture, id=capture_id)
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    if request.method == "POST":
        notes = request.POST['detail']
        if 'date' in request.POST:
            date = request.POST['date']
            if not date:
                date = None
            capture.due_date = date
        if 'anytime' in request.POST:
            capture.due_date = None
            capture.any_time = 1
        project = request.POST['project']
        if project:
            capture.project = request.POST['project']
            capture.category = 1
        capture.notes = notes
        capture.save()
        return HttpResponseRedirect(reverse('capture:index', args=None))
    context = {'capture': capture,
               'amount': amount,
               'bin_amount': bin_amount,
               'all_project_items': all_project_items}
    return render(request, 'capture/detail.html', context)    

# all is non-functional atm
def all(request):
    all_capture_list = Capture.objects.order_by('-capture_date')
    output = ', '.join([c.capture_text for c in all_capture_list])
    return HttpResponse(output)

def capture(request):
    print("capture started")
    textinput = request.POST['capture']
    c = Capture(capture_text=textinput, capture_date=timezone.now())
    c.save()
    print(c, "saved!")
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('capture:index', args=None))

def delete(request,capture_id =None):
    object = Capture.objects.get(id=capture_id)
    if object.category == 8:
        object.delete()
        return HttpResponseRedirect(reverse('capture:paper_bin', args=None))
    else:
        object.category = 8
        object.save()
        return redirect(request.META['HTTP_REFERER'])

def undelete(request,capture_id =None):
    object = Capture.objects.get(id=capture_id)
    if object.category == 8:
        object.category = 0
        object.status = 0
        object.save()
        return redirect(request.META['HTTP_REFERER'])
    elif object.status == 1:
        object.status = 0
        object.save()
        return redirect(request.META['HTTP_REFERER'])

def logbook(request):
    all_done_list = Capture.objects.exclude(category=8).filter(status=1).order_by('-capture_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_done_list': all_done_list,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/logbook.html', context)

def log_item(request,capture_id =None):
    object = Capture.objects.get(id=capture_id)
    object.status = 1
    object.save()
    return redirect(request.META['HTTP_REFERER'])

def today(request):
    all_today_list = Capture.objects.exclude(category=8).filter(status=0, due_date__range=["2011-01-31",datetime.date.today()]).order_by('-capture_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_today_list': all_today_list,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/today.html', context)

def calendar(request):
    all_calendar_items = Capture.objects.exclude(category=8).filter(status=0, due_date__range=[datetime.date.today(), "9011-01-31"]).order_by('due_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_calendar_items': all_calendar_items,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/calendar.html', context)

def anytime(request):
    all_anytime_list = Capture.objects.filter(status=0, any_time=1).order_by('-capture_date')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_anytime_list': all_anytime_list,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/anytime.html', context)

def projects(request):
    all_project_items = Capture.objects.filter(status=0, category=1).order_by('project')
    amount = Capture.objects.filter(status=0, category=0).exclude(due_date__range=["2011-01-31","9011-01-31"]).count()
    bin_amount = Capture.objects.filter(category=8).count()
    context = {
        'all_project_items': all_project_items,
        'amount': amount,
        'bin_amount': bin_amount,
               }
    return render(request, 'capture/projects.html', context)

capture/templates/base_generic.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'capture/images/favicon.png' %}"/>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'capture/style.css' %}">
        
        <title>{% block title %}Getting Things Done{% endblock %}</title>
    </head>
    <body>
       
<div class="flex-container">
    <div class="menu-left">
        <div>
            <a href= {% url 'capture:index' %}><i class="fas fa-inbox fa-fw"></i> Inbox ({{ amount }})</a>
        </div>
        <div>
            <a href= {% url 'capture:today' %}><i class="fas fa-star fa-fw"></i> Today</a>
        </div>
        <div>
            <a href= {% url 'capture:calendar' %}><i class="fas fa-calendar-alt fa-fw"></i> Planned</a>
        </div>
        <div>
            <a href= {% url 'capture:anytime' %}><i class="fas fa-folder-open fa-fw"></i> Anytime</a>
        </div>
        <div>
            <a href= {% url 'capture:logbook' %}><i class="fas fa-book fa-fw"></i> Logbook</a>
        </div>
         <div>
            <a href= {% url 'capture:paper_bin' %}><i class="fas fa-recycle fa-fw"></i> Paper bin ({{ bin_amount }})</a>
        </div>
        <div>
            <a href= {% url 'capture:projects' %}><i class="fas fa-tasks fa-fw"></i> Projects </a>
        </div>
    </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

capture/templates/capture/anytime.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

    <div class="item">   

{% if all_anytime_list %}
        <h1>Anytime</h1>
        <p>
            <ul class="list-group" style="min-width: 307px">
            {% for capture in all_anytime_list %}
                <li class="list-group-item">
                    <span title="Mark as finished"><a href="{% url 'capture:log_item' capture.id%}"><img src="{% static 'capture/images/checked.png' %}" align="left" border="0" ></a></span>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' capture.id %} style="color:black">{{ capture.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                    <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' capture.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span></li>
            {% endfor %}
            </ul>
        </p>
{% endif %}

    </div>
    <div class="menu-right">
        This is the right menu        
    </div>

{% endblock content%}

capture/templates/capture/calendar.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

    <div class="item">   

{% if all_calendar_items %}
        <h1>Calendar</h1>
        <p>
        {% regroup all_calendar_items by due_date as date_list %}

        {% for due_date in date_list %}
            <h3>{{ due_date.grouper }}</h3>
            <ul class="list-group" style="min-width: 307px">
                {% for item in due_date.list %}
                    <li class="list-group-item">
                        <span title="Mark as finished"><a href="{% url 'capture:log_item' item.id%}"><img src="{% static 'capture/images/checked.png' %}" align="left" border="0" ></a></span>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' item.id %} style="color:black">{{ item.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                    <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' item.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span>
                    </li>
                {% endfor %}
                <br>
            </ul>
        {% endfor %}
        </p>
{% endif %}

    </div>
    <div class="menu-right">
        This is the right menu        
    </div>

{% endblock content%}

capture/templates/capture/detail.html
{% extends "base_generic.html" %}

{% block title %}GTD - Details View{% endblock title%}

{% block content %}
{% regroup all_project_items by project as project_list %}
<div class="item">   

<h1>{{ capture.capture_text }}</h1> 

<form action="/capture/{{capture.id}}/" method="POST"> 
  <div class="form-row">
    <div class="form-group col-md-3" style="min-width: 300px">
      <label for="inputNextAction">Next action:</label>
      {% csrf_token %}
      <input type="text" class="form-control" name="detail" value="{% if capture.notes %}{{capture.notes}}{% endif %}" autofocus>
    </div>
    <div class="form-group col-md-3" style="max-width: 300px">
      <label for="project-list-choice">Project:</label><br>
      <input list="project-list" style="min-width: 200px" class="col-md-3 custom-select custom-select-md" id="project-list-choice" name="project" value="{% if capture.project %}{{capture.project}}{% endif %}"/>
      <datalist id="project-list">
        {% spaceless %}
        {% for project in project_list %}
          <option value="{{ project.grouper }}">
        {% endfor %}
        {% endspaceless %}
      </datalist>
    </div>
    <div class="form-group col-md-3" style="max-width: 300px">
      <label for="chooseDate">When:</label>
      <input type="date" class="form-control" id="date" name="date" value="{% if capture.due_date %}{{capture.due_date|date:"Y-m-d"}}{% endif %}">
      <input type="checkbox" class="form-check-inline" id="anytime" name="anytime" value="anytime"><label for="anytime">Anytime</label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
</form>
</div>
<script>
window.onload = function() {
  if ({{ capture.any_time }} == 1) {
    document.getElementById('anytime').checked = true;
    document.getElementById('date').disabled = true;
  }
};

document.getElementById('anytime').onchange = function() {
  if (document.getElementById('anytime').checked == true){
    document.getElementById('date').disabled = true;
  } else {
    document.getElementById('date').disabled = false;
  }
  
};
</script>

{% endblock %}

capture/templates/capture/index.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

<div class="item">   

{% if all_capture_list %}
        <h1>Inbox</h1>
        <form class="form-inline" action="{% url 'capture:capture' %}" method="POST">
            <div class="form-group mr-sm-2 mb-2">
                {% csrf_token %}
                <input type="text" class="form-control" name="capture" value="" autofocus>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Submit</button>
            
        </form>
        <p>
            <ul class="list-group">
            {% for capture in all_capture_list %}
                <li class="list-group-item">
                    <span title="Mark as finished"><a href="{% url 'capture:log_item' capture.id%}"><img src="{% static 'capture/images/checked.png' %}" align="left" border="0" ></a></span>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' capture.id %} style="color:black">{{ capture.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                    <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' capture.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span></li>
            {% endfor %}
            </ul>
        </p>
{% endif %}

{% if paper_bin_list %}
    <h1>Paper bin</h1>
        <p>
            <ul class="list-group" style="min-width: 307px">
            {% for capture in paper_bin_list %}
                <li class="list-group-item">
                <span title="Restore"><a href="{% url 'capture:undelete' capture.id%}"><img src="{% static 'capture/images/undelete.png' %}" align="left" border="0" ></span></a>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' capture.id %} style="color:black">{{ capture.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                <span title="Delete forever!"><a href="{% url 'capture:delete' capture.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span></li>
            {% endfor %}
            </ul>
        </p>
{% endif %}

{% if not paper_bin_list and not all_capture_list %}
    <h1>Inbox</h1>
        <form class="form-inline" action="{% url 'capture:capture' %}" method="POST">
            <div class="form-group mr-sm-2 mb-2">
                {% csrf_token %}
                <input type="text" class="form-control" name="capture" value="" autofocus>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Submit</button>
            
        </form>
{% endif %}

    </div>
</div>

{% endblock %}

capture/templates/capture/logbook.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

    <div class="item">   
    <h1>Logbook</h1>
{% if all_done_list %}
        <p>
            <ul class="list-group" style="min-width: 307px">
            {% for capture in all_done_list %}
                <li class="list-group-item">
                <span title="Restore"><a href="{% url 'capture:undelete' capture.id%}"><img src="{% static 'capture/images/undelete.png' %}" align="left" border="0" ></span></a>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' capture.id %} style="color:black">{{ capture.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' capture.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span></li>
            {% endfor %}
            </ul>
        </p>
{% endif %}

    </div>
    <div class="menu-right">
        This is the right menu        
    </div>


{% endblock content%}

capture/templates/capture/projects.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

    <div class="item">   

{% if all_project_items %}
        <h1>My Projects</h1>
        <p>
        {% regroup all_project_items by project as project_list %}

        {% for project in project_list %}
            
            <h3>{{ project.grouper }}</h3>
            <ul class="list-group" style="min-width: 307px">
                {% for item in project.list %}
                    <li class="list-group-item">                  
                    <span title="Mark as finished"><a href="{% url 'capture:log_item' item.id%}"><img src="{% static 'capture/images/checked.png' %}" align="left" border="0" ></a></span>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' item.id %} style="color:black">{{ item.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                    <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' item.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span>
                    </li>
                {% endfor %}
                <br>
            </ul>
        {% endfor %}
        </p>

{% endif %}

    </div>
    <div class="menu-right">
        This is the right menu        
    </div>

{% endblock content%}

capture/templates/capture/today.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}

<div class="item">   

{% if all_today_list %}
        <h1>Today</h1>
        <p>
            <ul class="list-group" style="min-width: 307px">
            {% for capture in all_today_list %}
                <li class="list-group-item">
                    <span title="Mark as finished"><a href="{% url 'capture:log_item' capture.id%}"><img src="{% static 'capture/images/checked.png' %}" align="left" border="0" ></a></span>&nbsp;&nbsp;&nbsp;<a href={% url 'capture:detail' capture.id %} style="color:black">{{ capture.capture_text }}</a>&nbsp;&nbsp;&nbsp;
                    <span title="Delete to Paper Bin"><a href="{% url 'capture:delete' capture.id%}"><img src="{% static 'capture/images/cancel.png' %}" align="right" border="0" ></a></span></li>            {% endfor %}
            </ul>
        </p>
{% endif %}

    </div>
    <div class="menu-right">
        This is the right menu        
    </div>
</div>

{% endblock content%}